FROM golang:1.23

WORKDIR /usr/src/app

RUN go install github.com/mitranim/gow@latest
# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY init.bash /root/
RUN bash ~/init.bash 

EXPOSE 8080/tcp
EXPOSE 8081/tcp